### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by cristianserban** [LivotovLabs/AutoForms#1]
I want to map a one to many relationship... do you have any work in progress regarding this ?

**Comment by livotov** [comment]
yeah, that's the second phase once I finish with simple field types and validations. Currently finishing impleneting suppoprt for File type or Collection<File> for uploading single/multiple files from within a form.

As for one to many feature - would be interesting to see your ideas on this as well. Currently I was thinking on support for both inline field (where you have smth like a table inside a main form) and external popup form, where you have a button in the main form which open a dialog window for data collection editing. Maybe you have some thoughts on how this may look and work better?

**Comment by cristianserban** [comment]
the inline approach is the one made also by JPACONTAINER but I don't like it very much. 
I try to use a popup in which i load an other form. it gives me more options......

**Comment by gloax29** [comment]
hello, 
it's a little late, I come back. 
with some changes
types:    Aeratext,   component 
component allows you to add components of all types (Upload, Embedded, ...) 
Button, 
possiblility of adding a listener on external Each one. Button.ClickListener 
internal upload method: 
setInternUpload () 
upload if used, name and download Imediat File recovery by getfileUpload () method.
this gives greater flexibility to create forms. I compiled 7.3 and it works well.
